apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: aks-sample
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: aks-sample
  template:  
    metadata: # Dictionary
      name: aks-sample
      labels: # Dictionary
        app: aks-sample  # Key value paids
    spec:
      containers: # List
        - name: aks-sample-container
          image: azaksacr1.azurecr.io/aks-sample:31
          ports: 
            - containerPort: 80  

---

apiVersion: v1
kind: Service 
metadata:
  name: aks-sample-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: aks-sample
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
